name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'  # Specify the Flutter version

      - name: Install dependencies
        run: flutter pub get

      # Optional: Uncomment to enforce code formatting
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
